version: '2'

services:
  server:
    image: tornadocash/relayer
    restart: always
    command: server
    env_file: .env
    expose: [ 8000 ]
    ports: [ 8000 ]
    environment:
      REDIS_URL: redis://redis/0
      nginx_proxy_read_timeout: 600
    depends_on:
      - redis

  treeWatcher:
    image: tornadocash/relayer
    restart: always
    command: treeWatcher
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

  priceWatcher:
    image: tornadocash/relayer
    restart: always
    command: priceWatcher
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

  worker1:
    image: tornadocash/relayer
    restart: always
    command: worker
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

#  worker2:
#    image: tornadocash/relayer
#    restart: always
#    command: worker
#    env_file: .env
#    environment:
#      PRIVATE_KEY: qwe
#      REDIS_URL: redis://redis/0

  redis:
    image: redis
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

volumes:
  redis:

