version: '2'

services:
  kovan:
    image: tornadocash/relayer
    restart: always
    command: server
    env_file: .env
    expose: [ 8000 ]
    environment:
      VIRTUAL_HOST: example.duckdns.org
      LETSENCRYPT_HOST: example.duckdns.org
      REDIS_URL: redis://redis/0
      nginx_proxy_read_timeout: 600
    depends_on:
      - redis

  tree-monitor:
    image: tornadocash/relayer
    restart: always
    command: tree-monitor
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

  worker1:
    image: tornadocash/relayer
    restart: always
    command: worker
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

#  worker2:
#    image: tornadocash/relayer
#    restart: always
#    command: worker
#    env_file: .env
#    environment:
#      PRIVATE_KEY: qwe
#      REDIS_URL: redis://redis/0

  redis:
    image: redis
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    logging:
      driver: none

  dockergen:
    image: poma/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
    volumes_from:
      - nginx
      - dockergen

volumes:
  conf:
  vhost:
  html:
  certs:
  redis:
