version: '2'

services:
  relayer:
    build: ./
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: kovan.tornado.cash
      LETSENCRYPT_HOST: kovan.tornado.cash
    env_file: ./.env

  monitor:
    image: arefaslani/docker-telegram-notifier
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env

networks:
  default:
    external:
      name: frontend_default